spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.87.69}:${DB_PORT:5432}/${DB_NAME:task1}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

logging:
  pattern:
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS XXX'
  level:
    root: INFO
    com:
      sla.sla.moneytrans: DEBUG
  file:
    name: ${LOG_PATH:/home/datadrive/logs/task1/}${LOGFILE:today.log}
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_PATH:/home/datadrive/logs/task1/}%d{ddMMyyyy}.%i.log
      max-history: 60
      max-file-size: 800MB
